######################################################################
# Automatically generated by qmake (2.01a) ven. 20. juil. 02:13:30 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainWindow.h
SOURCES += main.cpp mainWindow.cpp
RESOURCES += FolderHash.qrc
